CREATE INDEX IF NOT EXISTS "paper_orders_status_idx" ON "paper_orders" ("CREATED");
CREATE INDEX IF NOT EXISTS "paper_trades_orderId_idx" ON "paper_trades" ("() => paperOrders.id");
CREATE INDEX IF NOT EXISTS "ai_models_status_idx" ON "ai_models" ("DRAFT");
CREATE INDEX IF NOT EXISTS "risk_events_orderId_idx" ON "risk_events" ("() => orders.id");
CREATE INDEX IF NOT EXISTS "executions_orderId_idx" ON "executions" ("() => orders.id");
CREATE INDEX IF NOT EXISTS "executions_portfolioId_idx" ON "executions" ("() => portfolios.id");
CREATE INDEX IF NOT EXISTS "positions_portfolioId_idx" ON "positions" ("() => portfolios.id");
CREATE INDEX IF NOT EXISTS "orders_portfolioId_idx" ON "orders" ("() => portfolios.id");
CREATE INDEX IF NOT EXISTS "orders_status_idx" ON "orders" ("CREATED");
CREATE INDEX IF NOT EXISTS "trades_portfolioId_idx" ON "trades" ("() => portfolios.id");
CREATE INDEX IF NOT EXISTS "trades_orderId_idx" ON "trades" ("() => orders.id");
CREATE INDEX IF NOT EXISTS "ai_recommendations_decisionId_idx" ON "ai_recommendations" ("() => aiDecisions.id");
CREATE INDEX IF NOT EXISTS "strategy_rules_strategyId_idx" ON "strategy_rules" ("() => strategies.id");
CREATE INDEX IF NOT EXISTS "strategy_executions_strategyId_idx" ON "strategy_executions" ("() => strategies.id");
CREATE INDEX IF NOT EXISTS "strategy_executions_decisionId_idx" ON "strategy_executions" ("() => aiDecisions.id");
CREATE INDEX IF NOT EXISTS "strategy_results_executionId_idx" ON "strategy_results" ("() => strategyExecutions.id");
CREATE INDEX IF NOT EXISTS "research_reports_decisionId_idx" ON "research_reports" ("() => aiDecisions.id");
CREATE INDEX IF NOT EXISTS "research_reports_strategyId_idx" ON "research_reports" ("() => strategies.id");
CREATE INDEX IF NOT EXISTS "memory_events_sessionId_idx" ON "memory_events" ("() => memorySessions.id");
CREATE INDEX IF NOT EXISTS "brain_sessions_completedAt_idx" ON "brain_sessions" ("completed_at");
CREATE INDEX IF NOT EXISTS "brain_assignments_completedAt_idx" ON "brain_assignments" ("completed_at");
CREATE INDEX IF NOT EXISTS "tournament_matches_completedAt_idx" ON "tournament_matches" ("completed_at");
CREATE INDEX IF NOT EXISTS "ai_learning_sessions_completedAt_idx" ON "ai_learning_sessions" ("completed_at");
CREATE INDEX IF NOT EXISTS "ai_learning_events_sessionId_idx" ON "ai_learning_events" ("session_id");
CREATE INDEX IF NOT EXISTS "strategy_lifecycles_approvalStatus_idx" ON "strategy_lifecycles" ("approval_status");
CREATE INDEX IF NOT EXISTS "ai_model_lifecycles_approvalStatus_idx" ON "ai_model_lifecycles" ("approval_status");
CREATE INDEX IF NOT EXISTS "strategy_reports_strategyId_idx" ON "strategy_reports" ("strategy_id");
CREATE INDEX IF NOT EXISTS "strategy_governance_status_idx" ON "strategy_governance" ("Draft");
CREATE INDEX IF NOT EXISTS "strategy_review_requests_status_idx" ON "strategy_review_requests" ("Open");
CREATE INDEX IF NOT EXISTS "strategy_compliance_status_idx" ON "strategy_compliance" ("Compliant");
CREATE INDEX IF NOT EXISTS "strategy_audit_logs_strategyId_idx" ON "strategy_audit_logs" ("strategy_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_walletId_idx" ON "learning_trigger" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_portfolioId_idx" ON "learning_trigger" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_correlationId_idx" ON "learning_trigger" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_status_idx" ON "learning_trigger" ("CREATED");
CREATE INDEX IF NOT EXISTS "learning_dispatch_walletId_idx" ON "learning_dispatch" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_dispatch_portfolioId_idx" ON "learning_dispatch" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_dispatch_correlationId_idx" ON "learning_dispatch" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_acknowledgement_walletId_idx" ON "learning_acknowledgement" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_acknowledgement_portfolioId_idx" ON "learning_acknowledgement" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_acknowledgement_correlationId_idx" ON "learning_acknowledgement" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_retry_walletId_idx" ON "learning_retry" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_retry_portfolioId_idx" ON "learning_retry" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_retry_correlationId_idx" ON "learning_retry" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_audit_walletId_idx" ON "learning_trigger_audit" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_audit_portfolioId_idx" ON "learning_trigger_audit" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_audit_correlationId_idx" ON "learning_trigger_audit" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_event_walletId_idx" ON "learning_trigger_event" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_event_portfolioId_idx" ON "learning_trigger_event" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_trigger_event_correlationId_idx" ON "learning_trigger_event" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_dead_letter_walletId_idx" ON "learning_dead_letter" ("wallet_id");
CREATE INDEX IF NOT EXISTS "learning_dead_letter_portfolioId_idx" ON "learning_dead_letter" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "learning_dead_letter_correlationId_idx" ON "learning_dead_letter" ("correlation_id");
CREATE INDEX IF NOT EXISTS "learning_dead_letter_status_idx" ON "learning_dead_letter" ("DEAD_LETTER");
CREATE INDEX IF NOT EXISTS "evolution_trigger_walletId_idx" ON "evolution_trigger" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_portfolioId_idx" ON "evolution_trigger" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_correlationId_idx" ON "evolution_trigger" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_status_idx" ON "evolution_trigger" ("CREATED");
CREATE INDEX IF NOT EXISTS "evolution_dispatch_walletId_idx" ON "evolution_dispatch" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_dispatch_portfolioId_idx" ON "evolution_dispatch" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_dispatch_correlationId_idx" ON "evolution_dispatch" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_acknowledgement_walletId_idx" ON "evolution_acknowledgement" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_acknowledgement_portfolioId_idx" ON "evolution_acknowledgement" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_acknowledgement_correlationId_idx" ON "evolution_acknowledgement" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_retry_walletId_idx" ON "evolution_retry" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_retry_portfolioId_idx" ON "evolution_retry" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_retry_correlationId_idx" ON "evolution_retry" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_audit_walletId_idx" ON "evolution_trigger_audit" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_audit_portfolioId_idx" ON "evolution_trigger_audit" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_audit_correlationId_idx" ON "evolution_trigger_audit" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_event_walletId_idx" ON "evolution_trigger_event" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_event_portfolioId_idx" ON "evolution_trigger_event" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_trigger_event_correlationId_idx" ON "evolution_trigger_event" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_dead_letter_walletId_idx" ON "evolution_dead_letter" ("wallet_id");
CREATE INDEX IF NOT EXISTS "evolution_dead_letter_portfolioId_idx" ON "evolution_dead_letter" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "evolution_dead_letter_correlationId_idx" ON "evolution_dead_letter" ("correlation_id");
CREATE INDEX IF NOT EXISTS "evolution_dead_letter_status_idx" ON "evolution_dead_letter" ("DEAD_LETTER");
CREATE INDEX IF NOT EXISTS "lifecycle_completion_walletId_idx" ON "lifecycle_completion" ("wallet_id");
CREATE INDEX IF NOT EXISTS "lifecycle_completion_portfolioId_idx" ON "lifecycle_completion" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "lifecycle_completion_correlationId_idx" ON "lifecycle_completion" ("correlation_id");
CREATE INDEX IF NOT EXISTS "qa_test_suite_aiModelId_idx" ON "qa_test_suite" ("MOD-001");
CREATE INDEX IF NOT EXISTS "qa_test_suite_walletId_idx" ON "qa_test_suite" ("wallet_id");
CREATE INDEX IF NOT EXISTS "qa_test_suite_portfolioId_idx" ON "qa_test_suite" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "qa_test_suite_status_idx" ON "qa_test_suite" ("PASSED");
CREATE INDEX IF NOT EXISTS "qa_test_suite_correlationId_idx" ON "qa_test_suite" ("correlation_id");
CREATE INDEX IF NOT EXISTS "qa_test_suite_aiModelId_status_idx" ON "qa_test_suite" ("MOD-001", "PASSED");
CREATE INDEX IF NOT EXISTS "qa_domain_result_aiModelId_idx" ON "qa_domain_result" ("MOD-001");
CREATE INDEX IF NOT EXISTS "qa_domain_result_walletId_idx" ON "qa_domain_result" ("wallet_id");
CREATE INDEX IF NOT EXISTS "qa_domain_result_portfolioId_idx" ON "qa_domain_result" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "qa_domain_result_status_idx" ON "qa_domain_result" ("PASSED");
CREATE INDEX IF NOT EXISTS "qa_domain_result_correlationId_idx" ON "qa_domain_result" ("correlation_id");
CREATE INDEX IF NOT EXISTS "qa_domain_result_aiModelId_status_idx" ON "qa_domain_result" ("MOD-001", "PASSED");
CREATE INDEX IF NOT EXISTS "qa_certification_report_aiModelId_idx" ON "qa_certification_report" ("MOD-ALL");
CREATE INDEX IF NOT EXISTS "qa_certification_report_walletId_idx" ON "qa_certification_report" ("wallet_id");
CREATE INDEX IF NOT EXISTS "qa_certification_report_portfolioId_idx" ON "qa_certification_report" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "qa_certification_report_correlationId_idx" ON "qa_certification_report" ("correlation_id");
CREATE INDEX IF NOT EXISTS "qa_audit_log_aiModelId_idx" ON "qa_audit_log" ("MOD-001");
CREATE INDEX IF NOT EXISTS "qa_audit_log_walletId_idx" ON "qa_audit_log" ("wallet_id");
CREATE INDEX IF NOT EXISTS "qa_audit_log_portfolioId_idx" ON "qa_audit_log" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "qa_audit_log_correlationId_idx" ON "qa_audit_log" ("correlation_id");
CREATE INDEX IF NOT EXISTS "system_boot_status_idx" ON "system_boot" ("BOOTING");
CREATE INDEX IF NOT EXISTS "genesis_session_status_idx" ON "genesis_session" ("INITIATED");
CREATE INDEX IF NOT EXISTS "workspace_registry_status_idx" ON "workspace_registry" ("REGISTERED");
CREATE INDEX IF NOT EXISTS "ai_registry_status_idx" ON "ai_registry" ("OFF");
CREATE INDEX IF NOT EXISTS "wallet_registry_status_idx" ON "wallet_registry" ("ZERO_STATE_INITIALIZED");
CREATE INDEX IF NOT EXISTS "system_events_correlationId_idx" ON "system_events" ("correlation_id");
CREATE INDEX IF NOT EXISTS "boot_events_correlationId_idx" ON "boot_events" ("correlation_id");
CREATE INDEX IF NOT EXISTS "qa_benchmark_record_aiModelId_idx" ON "qa_benchmark_record" ("MOD-001");
CREATE INDEX IF NOT EXISTS "qa_benchmark_record_walletId_idx" ON "qa_benchmark_record" ("wallet_id");
CREATE INDEX IF NOT EXISTS "qa_benchmark_record_portfolioId_idx" ON "qa_benchmark_record" ("portfolio_id");
CREATE INDEX IF NOT EXISTS "qa_benchmark_record_status_idx" ON "qa_benchmark_record" ("PASSED");
CREATE INDEX IF NOT EXISTS "qa_benchmark_record_correlationId_idx" ON "qa_benchmark_record" ("correlation_id");
CREATE INDEX IF NOT EXISTS "qa_benchmark_record_aiModelId_status_idx" ON "qa_benchmark_record" ("MOD-001", "PASSED");
CREATE INDEX IF NOT EXISTS "trading_calendar_status_idx" ON "trading_calendar" ("VERIFIED");
CREATE INDEX IF NOT EXISTS "master_registry_status_idx" ON "master_registry" ("VALIDATED");
CREATE INDEX IF NOT EXISTS "startup_checklist_status_idx" ON "startup_checklist" ("PASSED");
CREATE INDEX IF NOT EXISTS "treasury_status_idx" ON "treasury" ("ACTIVE");
CREATE INDEX IF NOT EXISTS "capital_mint_status_idx" ON "capital_mint" ("MINTED");
CREATE INDEX IF NOT EXISTS "capital_allocation_status_idx" ON "capital_allocation" ("APPROVED");
CREATE INDEX IF NOT EXISTS "capital_reservation_status_idx" ON "capital_reservation" ("ACTIVE");
CREATE INDEX IF NOT EXISTS "treasury_lifecycle_status_idx" ON "treasury_lifecycle" ("ACTIVE");
CREATE INDEX IF NOT EXISTS "paper_live_treasury_status_idx" ON "paper_live_treasury" ("ACTIVE");
CREATE INDEX IF NOT EXISTS "treasury_certificates_walletId_idx" ON "treasury_certificates" ("wallet_id");
CREATE INDEX IF NOT EXISTS "treasury_certificates_aiModelId_idx" ON "treasury_certificates" ("ai_model_id");
CREATE INDEX IF NOT EXISTS "capital_flow_inspector_status_idx" ON "capital_flow_inspector" ("IN_PROGRESS");
CREATE INDEX IF NOT EXISTS "ai_activation_status_idx" ON "ai_activation" ("REGISTERED");
CREATE INDEX IF NOT EXISTS "ai_runtime_status_idx" ON "ai_runtime" ("OFF");
CREATE INDEX IF NOT EXISTS "ai_runtime_license_status_idx" ON "ai_runtime_license" ("ACTIVE");
CREATE INDEX IF NOT EXISTS "ai_runtime_certificate_registry_status_idx" ON "ai_runtime_certificate_registry" ("VALID");
CREATE INDEX IF NOT EXISTS "master_data_proposals_approvedAt_idx" ON "master_data_proposals" ("approved_at");
CREATE INDEX IF NOT EXISTS "market_recovery_jobs_certificateId_idx" ON "market_recovery_jobs" ("certificate_id");
CREATE INDEX IF NOT EXISTS "market_recovery_jobs_completedAt_idx" ON "market_recovery_jobs" ("completed_at");
CREATE INDEX IF NOT EXISTS "research_evidence_correlationId_idx" ON "research_evidence" ("correlation_id");
CREATE INDEX IF NOT EXISTS "intelligence_sessions_correlationId_idx" ON "intelligence_sessions" ("correlation_id");
CREATE INDEX IF NOT EXISTS "strategy_registry_status_idx" ON "strategy_registry" ("ENABLED");
CREATE INDEX IF NOT EXISTS "strategy_candidates_status_idx" ON "strategy_candidates" ("PENDING_COMMITTEE_DECISION");
CREATE INDEX IF NOT EXISTS "committee_sessions_status_idx" ON "committee_sessions" ("ACTIVE");
CREATE INDEX IF NOT EXISTS "committee_members_status_idx" ON "committee_members" ("PENDING");
CREATE INDEX IF NOT EXISTS "execution_authorization_status_idx" ON "execution_authorization" ("PENDING");
CREATE INDEX IF NOT EXISTS "execution_queue_status_idx" ON "execution_queue" ("PENDING");
CREATE INDEX IF NOT EXISTS "execution_context_status_idx" ON "execution_context" ("RUNNING");
CREATE INDEX IF NOT EXISTS "execution_routing_status_idx" ON "execution_routing" ("ROUTED");
