export const POLICY_CATEGORIES = {
  RISK_LIMITS: "RISK_LIMITS",
  EXECUTIVE_APPROVAL: "EXECUTIVE_APPROVAL",
  COMPLIANCE_RULE: "COMPLIANCE_RULE",
  RATE_LIMIT: "RATE_LIMIT",
  CIRCUIT_BREAKER: "CIRCUIT_BREAKER",
  KILL_SWITCH: "KILL_SWITCH",
} as const;

export type PolicyCategoryValue = (typeof POLICY_CATEGORIES)[keyof typeof POLICY_CATEGORIES];

export const ENFORCEMENT_LEVELS = {
  STRICT_BLOCK: "STRICT_BLOCK",
  WARNING_ONLY: "WARNING_ONLY",
  APPROVAL_REQUIRED: "APPROVAL_REQUIRED",
} as const;

export type EnforcementLevelValue = (typeof ENFORCEMENT_LEVELS)[keyof typeof ENFORCEMENT_LEVELS];

export const EVALUATION_STATUSES = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  REQUIRES_APPROVAL: "REQUIRES_APPROVAL",
  CIRCUIT_BROKEN: "CIRCUIT_BROKEN",
  KILL_SWITCH_ACTIVE: "KILL_SWITCH_ACTIVE",
} as const;

export type EvaluationStatusValue = (typeof EVALUATION_STATUSES)[keyof typeof EVALUATION_STATUSES];

export const CIRCUIT_BREAKER_STATUSES = {
  CLOSED: "CLOSED",
  OPEN: "OPEN",
  HALF_OPEN: "HALF_OPEN",
} as const;

export type CircuitBreakerStatusValue = (typeof CIRCUIT_BREAKER_STATUSES)[keyof typeof CIRCUIT_BREAKER_STATUSES];

export const RUNTIME_GOVERNANCE_ERRORS = {
  KILL_SWITCH_TRIGGERED: "ERR_RUNTIME_GOVERNANCE_KILL_SWITCH_ACTIVE",
  CIRCUIT_BREAKER_TRIPPED: "ERR_RUNTIME_GOVERNANCE_CIRCUIT_BREAKER_OPEN",
  POLICY_VIOLATION: "ERR_RUNTIME_GOVERNANCE_POLICY_VIOLATION",
  UNAUTHORIZED_ACTION: "ERR_RUNTIME_GOVERNANCE_UNAUTHORIZED",
  APPROVAL_REQUIRED: "ERR_RUNTIME_GOVERNANCE_APPROVAL_REQUIRED",
  EXECUTION_PROHIBITED: "ERR_RUNTIME_GOVERNANCE_DIRECT_EXECUTION_PROHIBITED",
  INVALID_PAYLOAD: "ERR_RUNTIME_GOVERNANCE_INVALID_PAYLOAD",
} as const;
