export type WalletType =
  | "MASTER_WALLET"
  | "AI_MODEL_WALLET"
  | "STRATEGY_WALLET"
  | "PAPER_TRADING_WALLET"
  | "RESERVE_WALLET"
  | "SYSTEM_WALLET"
  | "TEST_WALLET"
  | "CUSTOM_WALLET";

export type TransactionType =
  | "DEPOSIT"
  | "WITHDRAW"
  | "TRANSFER"
  | "CREDIT"
  | "DEBIT"
  | "ADJUSTMENT"
  | "REVERSAL"
  | "LOCK"
  | "UNLOCK";

export type WalletStatus = "ACTIVE" | "FROZEN" | "LOCKED" | "TERMINATED";

export type TransactionStatus = "PENDING" | "SUCCESS" | "FAILED" | "CANCELLED";

export type PipelineStage =
  | "REQUEST"
  | "VALIDATE_GOVERNANCE"
  | "VALIDATE_WALLETS"
  | "VALIDATE_BALANCE"
  | "LOCK_FUNDS"
  | "RECORD_LEDGER"
  | "COMMIT_TRANSFER"
  | "READY";

export const WALLET_TYPES: Record<WalletType, WalletType> = {
  MASTER_WALLET: "MASTER_WALLET",
  AI_MODEL_WALLET: "AI_MODEL_WALLET",
  STRATEGY_WALLET: "STRATEGY_WALLET",
  PAPER_TRADING_WALLET: "PAPER_TRADING_WALLET",
  RESERVE_WALLET: "RESERVE_WALLET",
  SYSTEM_WALLET: "SYSTEM_WALLET",
  TEST_WALLET: "TEST_WALLET",
  CUSTOM_WALLET: "CUSTOM_WALLET",
};

export const TRANSACTION_TYPES: Record<TransactionType, TransactionType> = {
  DEPOSIT: "DEPOSIT",
  WITHDRAW: "WITHDRAW",
  TRANSFER: "TRANSFER",
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",
  ADJUSTMENT: "ADJUSTMENT",
  REVERSAL: "REVERSAL",
  LOCK: "LOCK",
  UNLOCK: "UNLOCK",
};

export const WALLET_PIPELINE_STAGES: Record<PipelineStage, PipelineStage> = {
  REQUEST: "REQUEST",
  VALIDATE_GOVERNANCE: "VALIDATE_GOVERNANCE",
  VALIDATE_WALLETS: "VALIDATE_WALLETS",
  VALIDATE_BALANCE: "VALIDATE_BALANCE",
  LOCK_FUNDS: "LOCK_FUNDS",
  RECORD_LEDGER: "RECORD_LEDGER",
  COMMIT_TRANSFER: "COMMIT_TRANSFER",
  READY: "READY",
};
