import React, { useState, useMemo } from 'react';
import { 
  Activity, BookOpen, Clock, PlayCircle, ShieldCheck, PieChart, Layers, Settings, FileText, CheckCircle,
  Search, Filter, Download, ExternalLink, ChevronDown, ChevronRight, AlertCircle, Check, X, ArrowUpRight, ArrowDownRight, RefreshCw, Eye, Database, Cpu, Lock, Terminal as TerminalIcon,
  Play, Pause, FastForward, RotateCcw, Award, CheckSquare, Globe, Server, Hash, FileCheck, ShieldAlert
} from 'lucide-react';
import { cn, formatCurrency } from '../lib/utils';
import { DataBoundary } from './ui/Feedback';
import { Button } from './ui/Button';

interface TradeJournalRecord {
  id: string;
  journalId: string;
  executionId: string;
  decisionId: string;
  committeeId: string;
  orderId: string;
  positionId: string;
  aiModel: string;
  strategy: string;
  committee: string;
  lab: string;
  exchange: string;
  segment: string;
  instrument: string;
  quantity: number;
  side: 'BUY' | 'SELL';
  entryPrice: number;
  exitPrice: number;
  entryTime: string;
  closedTime: string;
  holdingTime: string;
  returnPct: number;
  grossPnl: number;
  netPnl: number;
  commission: number;
  slippageBps: number;
  executionQuality: number; // e.g., 98 / 100
  riskScore: number; // 1-10
  confidence: number; // %
  knowledgeVersion: string;
  memorySnapshot: string;
  replayAvailable: boolean;
  evidenceId: string;
  auditStatus: string;
  certificateHash: string;
  decisionReason: string;
  tradeStatus: 'WIN' | 'LOSS' | 'BREAKEVEN' | 'REJECTED' | 'CANCELLED';
  timeline: { time: string; event: string; status: string }[];
  committeeVotes: { agent: string; vote: string; weight: number }[];
  riskSnapshot: { var: string; beta: number; maxDrawdown: string };
  memoryReferences: string[];
  knowledgeLinks: string[];
}

const MOCK_JOURNAL_RECORDS: TradeJournalRecord[] = [
  {
    id: 'TRD-9001',
    journalId: 'JNL-8841',
    executionId: 'EX-5510',
    decisionId: 'DEC-7712',
    committeeId: 'COM-9-V2',
    orderId: 'ORD-9001',
    positionId: 'POS-801',
    aiModel: 'ARINA-Omni-v3',
    strategy: 'Quantum Alpha Arb',
    committee: '9-Agent Quorum',
    lab: 'Stock Market Lab',
    exchange: 'NSE',
    segment: 'Equity Futures',
    instrument: 'RELIANCE.NS',
    quantity: 500,
    side: 'BUY',
    entryPrice: 2920.50,
    exitPrice: 2985.20,
    entryTime: '2026-08-03 09:15:22',
    closedTime: '2026-08-03 13:30:10',
    holdingTime: '4h 15m',
    grossPnl: 33500.00,
    netPnl: 32350.00,
    returnPct: 2.21,
    commission: 1150.00,
    slippageBps: -0.17,
    executionQuality: 98,
    riskScore: 2.1,
    confidence: 94,
    knowledgeVersion: 'v4.8.2',
    memorySnapshot: 'MEM-4492-VEC',
    replayAvailable: true,
    evidenceId: 'EVD-8891-SHA',
    auditStatus: 'VERIFIED',
    certificateHash: '0x88f91c3a9920182b447e1102948fbc102a991f810aa',
    decisionReason: 'Orderflow imbalance detected at VWAP support with positive institutional block accumulation.',
    tradeStatus: 'WIN',
    timeline: [
      { time: '09:15:22', event: 'Decision generated by ARINA-Omni-v3', status: 'SUCCESS' },
      { time: '09:15:25', event: '9/9 AI Committee Quorum Achieved', status: 'APPROVED' },
      { time: '09:15:28', event: 'Smart DMA Router dispatched to NSE', status: 'ROUTED' },
      { time: '09:15:30', event: 'Executed at ₹2,920.50 (Slippage -0.17 bps)', status: 'FILLED' }
    ],
    committeeVotes: [
      { agent: 'Macro Analyst', vote: 'APPROVE', weight: 0.95 },
      { agent: 'Risk Officer', vote: 'APPROVE', weight: 0.98 },
      { agent: 'Momentum Specialist', vote: 'APPROVE', weight: 0.92 }
    ],
    riskSnapshot: { var: '0.03%', beta: 0.85, maxDrawdown: '-0.42%' },
    memoryReferences: ['MEM-4492 (Reliance Q1 Breakout Pattern)', 'MEM-8810 (VWAP Bounce Rule)'],
    knowledgeLinks: ['KN-102 (Oil-to-Telecom Margin Expansion)', 'KN-391 (Index Rebalance Flow)']
  },
  {
    id: 'TRD-9002',
    journalId: 'JNL-8842',
    executionId: 'EX-5511',
    decisionId: 'DEC-7713',
    committeeId: 'COM-9-V2',
    orderId: 'ORD-9002',
    positionId: 'POS-802',
    aiModel: 'Market Analyst AI',
    strategy: 'MacroBreakout',
    committee: '9-Agent Quorum',
    lab: 'Stock Market Lab',
    exchange: 'NSE',
    segment: 'Equities',
    instrument: 'TCS.NS',
    quantity: 300,
    side: 'BUY',
    entryPrice: 3840.00,
    exitPrice: 3912.40,
    entryTime: '2026-08-03 09:45:00',
    closedTime: '2026-08-03 12:25:00',
    holdingTime: '2h 40m',
    grossPnl: 22120.00,
    netPnl: 21720.00,
    returnPct: 1.88,
    commission: 400.00,
    slippageBps: 0.26,
    executionQuality: 96,
    riskScore: 1.8,
    confidence: 91,
    knowledgeVersion: 'v4.8.2',
    memorySnapshot: 'MEM-3312-VEC',
    replayAvailable: true,
    evidenceId: 'EVD-8892-SHA',
    auditStatus: 'VERIFIED',
    certificateHash: '0x33129a8b11209482bf1092a83991048201',
    decisionReason: 'IT sector basket rotation inflow exceeding 3.2x relative volume baseline.',
    tradeStatus: 'WIN',
    timeline: [
      { time: '09:45:00', event: 'Signal scored by Market Analyst AI', status: 'SUCCESS' },
      { time: '09:45:04', event: 'Committee Quorum Approved (9/9)', status: 'APPROVED' },
      { time: '09:45:10', event: 'Pegged Limit Route to Dark Pool', status: 'FILLED' }
    ],
    committeeVotes: [
      { agent: 'Sector Rotator', vote: 'APPROVE', weight: 0.94 },
      { agent: 'Liquidity Evaluator', vote: 'APPROVE', weight: 0.90 }
    ],
    riskSnapshot: { var: '0.02%', beta: 0.91, maxDrawdown: '-0.25%' },
    memoryReferences: ['MEM-3312 (IT Sector Earnings Beat Rule)'],
    knowledgeLinks: ['KN-201 (NASDAQ Tech Correlation)']
  },
  {
    id: 'TRD-9003',
    journalId: 'JNL-8843',
    executionId: 'EX-5512',
    decisionId: 'DEC-7714',
    committeeId: 'COM-9-V2',
    orderId: 'ORD-9003',
    positionId: 'COM-POS-301',
    aiModel: 'GPT-5 Institutional',
    strategy: 'CPI Macro Continuation',
    committee: '9-Agent Quorum',
    lab: 'Commodity Market Lab',
    exchange: 'MCX India',
    segment: 'Commodity Futures',
    instrument: 'MCX_GOLD',
    quantity: 5,
    side: 'BUY',
    entryPrice: 71800.00,
    exitPrice: 72455.00,
    entryTime: '2026-08-03 10:00:15',
    closedTime: '2026-08-03 12:15:30',
    holdingTime: '2h 15m',
    grossPnl: 33275.00,
    netPnl: 32750.00,
    returnPct: 0.91,
    commission: 525.00,
    slippageBps: 0.12,
    executionQuality: 99,
    riskScore: 2.5,
    confidence: 98,
    knowledgeVersion: 'v4.8.2',
    memorySnapshot: 'MEM-9012-VEC',
    replayAvailable: true,
    evidenceId: 'EVD-8893-SHA',
    auditStatus: 'VERIFIED',
    certificateHash: '0x9012837a110294838192a83019283019aa',
    decisionReason: 'Global safe-haven demand surge following geopolitical risk premium update.',
    tradeStatus: 'WIN',
    timeline: [
      { time: '10:00:15', event: 'MCX Bullion signal validated', status: 'SUCCESS' },
      { time: '10:00:20', event: 'Committee Quorum Unanimous', status: 'APPROVED' },
      { time: '10:00:25', event: 'MCX Vault execution complete', status: 'FILLED' }
    ],
    committeeVotes: [
      { agent: 'Macro Analyst', vote: 'APPROVE', weight: 0.99 },
      { agent: 'Commodity Desk Lead', vote: 'APPROVE', weight: 0.98 }
    ],
    riskSnapshot: { var: '0.05%', beta: 0.45, maxDrawdown: '-0.15%' },
    memoryReferences: ['MEM-9012 (MCX Gold Safe Haven correlation)'],
    knowledgeLinks: ['KN-882 (Global Central Bank Gold Reserves)']
  },
  {
    id: 'TRD-9004',
    journalId: 'JNL-8844',
    executionId: 'EX-5513',
    decisionId: 'DEC-7715',
    committeeId: 'COM-9-V2',
    orderId: 'ORD-9004',
    positionId: 'POS-804',
    aiModel: 'Scalper AI Engine',
    strategy: 'MicroAlpha',
    committee: '9-Agent Quorum',
    lab: 'Stock Market Lab',
    exchange: 'NSE',
    segment: 'Equities',
    instrument: 'HDFCBANK.NS',
    quantity: 600,
    side: 'BUY',
    entryPrice: 1640.20,
    exitPrice: 1628.50,
    entryTime: '2026-08-03 11:10:00',
    closedTime: '2026-08-03 12:30:00',
    holdingTime: '1h 20m',
    grossPnl: -7020.00,
    netPnl: -7450.00,
    returnPct: -0.71,
    commission: 430.00,
    slippageBps: 0.45,
    executionQuality: 89,
    riskScore: 3.2,
    confidence: 86,
    knowledgeVersion: 'v4.8.2',
    memorySnapshot: 'MEM-1102-VEC',
    replayAvailable: true,
    evidenceId: 'EVD-8894-SHA',
    auditStatus: 'VERIFIED',
    certificateHash: '0x1102839a9920182b447e1102948fbc102a9',
    decisionReason: 'Pullback support bounce test at 50 EMA.',
    tradeStatus: 'LOSS',
    timeline: [
      { time: '11:10:00', event: 'Scalp entry triggered', status: 'SUCCESS' },
      { time: '11:10:05', event: 'Approved by 7/9 committee members', status: 'APPROVED' },
      { time: '12:30:00', event: 'Stop-loss hit at ₹1,628.50', status: 'STOPPED' }
    ],
    committeeVotes: [
      { agent: 'Risk Officer', vote: 'CAUTION', weight: 0.70 },
      { agent: 'Scalper Agent', vote: 'APPROVE', weight: 0.85 }
    ],
    riskSnapshot: { var: '0.06%', beta: 1.12, maxDrawdown: '-0.71%' },
    memoryReferences: ['MEM-1102 (HDFC Bank Support Failure Analysis)'],
    knowledgeLinks: ['KN-440 (Banking Sector Liquidity Deficit)']
  },
  {
    id: 'TRD-9005',
    journalId: 'JNL-8845',
    executionId: 'EX-5514',
    decisionId: 'DEC-7716',
    committeeId: 'COM-9-V2',
    orderId: 'ORD-9005',
    positionId: 'ETF-POS-201',
    aiModel: 'ARINA-Core-Engine',
    strategy: 'Index Rebalance Alpha',
    committee: '9-Agent Quorum',
    lab: 'ETF Market Lab',
    exchange: 'NSE_ETF',
    segment: 'ETF Units',
    instrument: 'NIFTYBEES.NS',
    quantity: 2500,
    side: 'BUY',
    entryPrice: 262.40,
    exitPrice: 268.10,
    entryTime: '2026-08-02 09:30:15',
    closedTime: '2026-08-03 11:30:00',
    holdingTime: '1d 2h',
    grossPnl: 14500.00,
    netPnl: 14250.00,
    returnPct: 2.17,
    commission: 250.00,
    slippageBps: -0.08,
    executionQuality: 99,
    riskScore: 1.2,
    confidence: 96,
    knowledgeVersion: 'v4.8.2',
    memorySnapshot: 'MEM-5521-VEC',
    replayAvailable: true,
    evidenceId: 'EVD-8895-SHA',
    auditStatus: 'VERIFIED',
    certificateHash: '0x5521839a9920182b447e1102948fbc102',
    decisionReason: 'Index rebalance inflow arbitrage capture.',
    tradeStatus: 'WIN',
    timeline: [
      { time: '09:30:15', event: 'Index rebalance trigger fired', status: 'SUCCESS' },
      { time: '09:30:20', event: 'Committee Quorum Approved', status: 'APPROVED' },
      { time: '11:30:00', event: 'Target profit reached', status: 'CLOSED' }
    ],
    committeeVotes: [
      { agent: 'ETF Quant Lead', vote: 'APPROVE', weight: 0.99 }
    ],
    riskSnapshot: { var: '0.01%', beta: 0.99, maxDrawdown: '-0.10%' },
    memoryReferences: ['MEM-5521 (Nifty Rebalance Tracking Error)'],
    knowledgeLinks: ['KN-092 (ETF Liquidity Mechanics)']
  }
];

const LIVE_EVENT_FEED = [
  { time: '13:30:10', event: 'Trade Closed', details: 'TRD-9001 closed with Net P&L +₹32,350.00', status: 'SUCCESS' },
  { time: '13:30:11', event: 'Replay Generated', details: 'REPLAY-9001 built with 1,420 price ticks', status: 'SUCCESS' },
  { time: '13:30:12', event: 'Certificate Created', details: 'Institutional Certificate CERT-9001 cryptographic SHA256 sealed', status: 'SUCCESS' },
  { time: '13:30:12', event: 'Risk Approved', details: 'VaR 0.03% verified against Constitution Article VII', status: 'SUCCESS' },
  { time: '13:30:13', event: 'Committee Approved', details: '9/9 quorum recorded and stored in Vector DB', status: 'SUCCESS' },
  { time: '13:30:14', event: 'Evidence Stored', details: 'Evidence Vault snapshot EVD-8891 committed to WORM storage', status: 'SUCCESS' },
  { time: '13:30:15', event: 'Knowledge Linked', details: 'Linked KN-102 & KN-391 to permanent trade journal', status: 'SUCCESS' }
];

export const TradeWorkspace = React.memo(() => {
  const [activeTab, setActiveTab] = useState<'DASHBOARD' | 'JOURNAL' | 'TIMELINE' | 'REPLAY' | 'EVIDENCE' | 'PERFORMANCE' | 'CERTIFICATES' | 'AUDIT' | 'INSPECTOR'>('JOURNAL');
  const [searchQuery, setSearchQuery] = useState('');
  const [labFilter, setLabFilter] = useState<string>('ALL');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');
  const [modelFilter, setModelFilter] = useState<string>('ALL');
  const [selectedTrade, setSelectedTrade] = useState<TradeJournalRecord | null>(MOCK_JOURNAL_RECORDS[0]);
  const [expandedRowId, setExpandedRowId] = useState<string | null>(null);
  const [bottomInspectorTab, setBottomInspectorTab] = useState<string>('TIMELINE');
  const [isPlayingReplay, setIsPlayingReplay] = useState(false);
  const [replaySpeed, setReplaySpeed] = useState(1);
  const [replayStep, setReplayStep] = useState(4);

  const filteredRecords = useMemo(() => {
    return MOCK_JOURNAL_RECORDS.filter(trd => {
      const matchesSearch = searchQuery === '' || 
        trd.instrument.toLowerCase().includes(searchQuery.toLowerCase()) ||
        trd.id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        trd.aiModel.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesLab = labFilter === 'ALL' || trd.lab === labFilter;
      const matchesStatus = statusFilter === 'ALL' || trd.tradeStatus === statusFilter;
      const matchesModel = modelFilter === 'ALL' || trd.aiModel === modelFilter;
      return matchesSearch && matchesLab && matchesStatus && matchesModel;
    });
  }, [searchQuery, labFilter, statusFilter, modelFilter]);

  // KPI Calculations
  const totalClosedTrades = MOCK_JOURNAL_RECORDS.length;
  const winningTrades = MOCK_JOURNAL_RECORDS.filter(t => t.tradeStatus === 'WIN').length;
  const losingTrades = MOCK_JOURNAL_RECORDS.filter(t => t.tradeStatus === 'LOSS').length;
  const winRate = ((winningTrades / totalClosedTrades) * 100).toFixed(1);
  const grossProfit = MOCK_JOURNAL_RECORDS.filter(t => t.grossPnl > 0).reduce((acc, t) => acc + t.grossPnl, 0);
  const grossLoss = MOCK_JOURNAL_RECORDS.filter(t => t.grossPnl < 0).reduce((acc, t) => acc + t.grossPnl, 0);
  const netPnl = MOCK_JOURNAL_RECORDS.reduce((acc, t) => acc + t.netPnl, 0);
  const avgConfidence = (MOCK_JOURNAL_RECORDS.reduce((acc, t) => acc + t.confidence, 0) / totalClosedTrades).toFixed(0);
  const avgEqs = (MOCK_JOURNAL_RECORDS.reduce((acc, t) => acc + t.executionQuality, 0) / totalClosedTrades).toFixed(1);
  const avgSlippage = (MOCK_JOURNAL_RECORDS.reduce((acc, t) => acc + t.slippageBps, 0) / totalClosedTrades).toFixed(2);

  const tabs = [
    { id: 'DASHBOARD', label: '1. Overview', icon: Activity },
    { id: 'JOURNAL', label: '2. Trade Journal', icon: BookOpen },
    { id: 'TIMELINE', label: '3. Timeline', icon: Clock },
    { id: 'REPLAY', label: '4. Replay', icon: PlayCircle },
    { id: 'EVIDENCE', label: '5. Evidence Vault', icon: FileText },
    { id: 'PERFORMANCE', label: '6. Performance', icon: PieChart },
    { id: 'CERTIFICATES', label: '7. Certificates', icon: Award },
    { id: 'AUDIT', label: '8. Audit', icon: CheckCircle },
    { id: 'INSPECTOR', label: '9. Inspector', icon: Settings },
  ];

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-terminal-bg text-white font-sans">
      <DataBoundary data={MOCK_JOURNAL_RECORDS} title="Enterprise Trade Journal & Forensic Memory System (EP15)">
        
        {/* TOP COMPACT NAVIGATION TABS (INSTITUTIONAL HEADER) */}
        <div className="bg-black border-b border-terminal-border px-3 py-1.5 flex items-center justify-between gap-2 overflow-x-auto shrink-0 font-mono">
          <div className="flex items-center gap-1.5">
            <span className="text-terminal-amber font-bold text-xs uppercase flex items-center gap-1 mr-2">
              <TerminalIcon className="w-3.5 h-3.5" /> Trade Journal:
            </span>
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as any)}
                  className={cn(
                    "px-2.5 py-1 rounded text-[10px] font-bold uppercase transition-all flex items-center gap-1.5 whitespace-nowrap",
                    activeTab === tab.id
                      ? "bg-terminal-amber text-black font-extrabold shadow-sm"
                      : "bg-white/5 text-terminal-muted hover:text-white hover:bg-white/10"
                  )}
                >
                  <Icon className="w-3 h-3" /> {tab.label}
                </button>
              );
            })}
          </div>
          <span className="text-[10px] text-terminal-green font-mono font-bold">SHA256 WORM VAULT SECURED</span>
        </div>

        {/* TOP KPI STRIP */}
        <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-12 gap-1.5 bg-black border-b border-terminal-border p-2 font-mono text-xs shrink-0">
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Closed Trades</span>
            <span className="text-white font-bold text-[11px]">{totalClosedTrades} Units</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Winning / Losing</span>
            <span className="text-terminal-green font-bold text-[11px]">{winningTrades}W / {losingTrades}L</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Win Rate</span>
            <span className="text-terminal-amber font-bold text-[11px]">{winRate}%</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Gross Profit</span>
            <span className="text-terminal-green font-bold text-[11px]">+{formatCurrency(grossProfit)}</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Gross Loss</span>
            <span className="text-terminal-red font-bold text-[11px]">{formatCurrency(grossLoss)}</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Net P&L</span>
            <span className={cn("font-bold text-[11px]", netPnl >= 0 ? "text-terminal-green" : "text-terminal-red")}>
              {netPnl >= 0 ? '+' : ''}{formatCurrency(netPnl)}
            </span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Avg Hold Time</span>
            <span className="text-white font-bold text-[11px]">3.2 Hrs</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Avg Confidence</span>
            <span className="text-terminal-blue font-bold text-[11px]">{avgConfidence}%</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Avg EQS Quality</span>
            <span className="text-terminal-green font-bold text-[11px]">{avgEqs}/100</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Avg Slippage</span>
            <span className="text-terminal-amber font-bold text-[11px]">{avgSlippage} bps</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">AI Approval</span>
            <span className="text-purple-300 font-bold text-[11px]">100% (9/9)</span>
          </div>
          <div className="p-1 bg-white/5 border border-terminal-border rounded">
            <span className="text-[9px] text-terminal-muted uppercase block">Integrity Hash</span>
            <span className="text-terminal-green font-bold text-[11px]">0x88F9...</span>
          </div>
        </div>

        {/* FILTER BAR (FOR JOURNAL & TABS) */}
        <div className="bg-terminal-panel border-b border-terminal-border px-3 py-1.5 flex flex-wrap items-center justify-between gap-2 shrink-0 font-mono text-xs">
          <div className="flex flex-wrap items-center gap-2">
            <div className="relative">
              <Search className="w-3.5 h-3.5 absolute left-2.5 top-2 text-terminal-muted" />
              <input
                type="text"
                placeholder="Search instrument, ID, AI model..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="bg-black border border-terminal-border rounded pl-8 pr-3 py-1 text-[11px] text-white focus:outline-none focus:border-terminal-amber w-60"
              />
            </div>

            <select
              value={labFilter}
              onChange={(e) => setLabFilter(e.target.value)}
              className="bg-black border border-terminal-border rounded px-2.5 py-1 text-[11px] text-white focus:outline-none"
            >
              <option value="ALL">All Labs</option>
              <option value="Stock Market Lab">Stock Market Lab</option>
              <option value="ETF Market Lab">ETF Market Lab</option>
              <option value="Commodity Market Lab">Commodity Market Lab</option>
            </select>

            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="bg-black border border-terminal-border rounded px-2.5 py-1 text-[11px] text-white focus:outline-none"
            >
              <option value="ALL">All Results (WIN/LOSS)</option>
              <option value="WIN">WIN Only</option>
              <option value="LOSS">LOSS Only</option>
            </select>

            <select
              value={modelFilter}
              onChange={(e) => setModelFilter(e.target.value)}
              className="bg-black border border-terminal-border rounded px-2.5 py-1 text-[11px] text-white focus:outline-none"
            >
              <option value="ALL">All AI Models</option>
              <option value="ARINA-Omni-v3">ARINA-Omni-v3</option>
              <option value="Market Analyst AI">Market Analyst AI</option>
              <option value="GPT-5 Institutional">GPT-5 Institutional</option>
              <option value="Scalper AI Engine">Scalper AI Engine</option>
            </select>
          </div>

          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => alert("Exporting Trade Journal CSV...")} className="h-6 text-[10px] px-2.5 gap-1 border border-terminal-border hover:bg-white/5">
              <Download className="w-3 h-3 text-terminal-amber" /> Export CSV
            </Button>
            <Button variant="outline" size="sm" onClick={() => alert("Exporting Trade Journal PDF Report...")} className="h-6 text-[10px] px-2.5 gap-1 border border-terminal-border hover:bg-white/5">
              <FileText className="w-3 h-3 text-terminal-blue" /> Export PDF
            </Button>
          </div>
        </div>

        {/* TAB 1: EXECUTIVE DASHBOARD */}
        {activeTab === 'DASHBOARD' && (
          <div className="flex-1 overflow-y-auto p-4 space-y-4 font-mono text-xs">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-terminal-panel border border-terminal-border p-3 rounded space-y-2">
                <span className="text-white font-bold uppercase text-[11px] flex items-center gap-1.5">
                  <Activity className="w-3.5 h-3.5 text-terminal-green" /> Lab Performance Comparison
                </span>
                <div className="space-y-2 pt-2">
                  <div className="p-2 bg-white/5 rounded border border-terminal-border flex justify-between items-center">
                    <div>
                      <strong className="text-white block">Stock Market Lab</strong>
                      <span className="text-[10px] text-terminal-muted">3 Active Strategies</span>
                    </div>
                    <span className="text-terminal-green font-bold">+₹3,82,500 (+3.83%)</span>
                  </div>
                  <div className="p-2 bg-white/5 rounded border border-terminal-border flex justify-between items-center">
                    <div>
                      <strong className="text-white block">ETF Market Lab</strong>
                      <span className="text-[10px] text-terminal-muted">2 Active Strategies</span>
                    </div>
                    <span className="text-terminal-green font-bold">+₹1,82,100 (+3.64%)</span>
                  </div>
                  <div className="p-2 bg-white/5 rounded border border-terminal-border flex justify-between items-center">
                    <div>
                      <strong className="text-white block">Commodity Market Lab</strong>
                      <span className="text-[10px] text-terminal-muted">3 MCX Futures Strategies</span>
                    </div>
                    <span className="text-terminal-green font-bold">+₹3,42,000 (+4.56%)</span>
                  </div>
                </div>
              </div>

              <div className="bg-terminal-panel border border-terminal-border p-3 rounded space-y-2">
                <span className="text-white font-bold uppercase text-[11px] flex items-center gap-1.5">
                  <Cpu className="w-3.5 h-3.5 text-purple-300" /> AI Model Alpha & Accuracy
                </span>
                <div className="space-y-2 pt-2">
                  <div className="p-2 bg-white/5 rounded border border-terminal-border flex justify-between items-center">
                    <div>
                      <strong className="text-purple-300 block">ARINA-Omni-v3</strong>
                      <span className="text-[10px] text-terminal-muted">Quantum Arb & Rebalance</span>
                    </div>
                    <span className="text-terminal-green font-bold">96.2% Win Rate</span>
                  </div>
                  <div className="p-2 bg-white/5 rounded border border-terminal-border flex justify-between items-center">
                    <div>
                      <strong className="text-purple-300 block">GPT-5 Institutional</strong>
                      <span className="text-[10px] text-terminal-muted">Macro Bullion & CPI</span>
                    </div>
                    <span className="text-terminal-green font-bold">94.8% Win Rate</span>
                  </div>
                  <div className="p-2 bg-white/5 rounded border border-terminal-border flex justify-between items-center">
                    <div>
                      <strong className="text-purple-300 block">Market Analyst AI</strong>
                      <span className="text-[10px] text-terminal-muted">Sector Rotation & Breakout</span>
                    </div>
                    <span className="text-terminal-green font-bold">89.4% Win Rate</span>
                  </div>
                </div>
              </div>

              <div className="bg-terminal-panel border border-terminal-border p-3 rounded space-y-2">
                <span className="text-white font-bold uppercase text-[11px] flex items-center gap-1.5">
                  <ShieldCheck className="w-3.5 h-3.5 text-terminal-amber" /> Risk & Constitution Health
                </span>
                <div className="space-y-2 pt-2 text-[11px]">
                  <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Max Portfolio VaR:</span><strong className="text-white">0.03% (Safe)</strong></div>
                  <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Average Risk Score:</span><strong className="text-terminal-green">2.1 / 10</strong></div>
                  <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Constitution Violations:</span><strong className="text-terminal-green">0 Detected</strong></div>
                  <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">WORM Audit Integrity:</span><strong className="text-terminal-green">100% Sealed</strong></div>
                  <div className="flex justify-between py-1"><span className="text-terminal-muted">Average Latency:</span><strong className="text-terminal-blue">9.4 ms</strong></div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: MAIN ENTERPRISE JOURNAL TABLE */}
        {activeTab === 'JOURNAL' && (
          <div className="flex-1 flex overflow-hidden">
            <div className="flex-1 flex flex-col overflow-hidden border-r border-terminal-border bg-black/30">
              <div className="flex-1 overflow-x-auto overflow-y-auto">
                <table className="w-full text-left border-collapse font-mono text-[10px]">
                  <thead className="bg-black text-terminal-muted uppercase sticky top-0 border-b border-terminal-border z-10">
                    <tr>
                      <th className="p-2">Expand</th>
                      <th className="p-2">Trade ID</th>
                      <th className="p-2">AI Model & Strategy</th>
                      <th className="p-2">Instrument</th>
                      <th className="p-2">Side & Qty</th>
                      <th className="p-2">Entry → Exit</th>
                      <th className="p-2">Net P&L</th>
                      <th className="p-2">Return %</th>
                      <th className="p-2">EQS</th>
                      <th className="p-2">Audit Status</th>
                      <th className="p-2 text-right">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-white/5">
                    {filteredRecords.map((trd) => {
                      const isSelected = selectedTrade?.id === trd.id;
                      const isExpanded = expandedRowId === trd.id;
                      return (
                        <React.Fragment key={trd.id}>
                          <tr 
                            onClick={() => setSelectedTrade(trd)}
                            className={cn(
                              "hover:bg-white/5 transition-colors cursor-pointer",
                              isSelected ? "bg-terminal-amber/10 border-l-2 border-terminal-amber" : ""
                            )}
                          >
                            <td className="p-2">
                              <button 
                                onClick={(e) => { e.stopPropagation(); setExpandedRowId(isExpanded ? null : trd.id); }}
                                className="p-1 hover:bg-white/10 rounded text-terminal-amber"
                              >
                                {isExpanded ? <ChevronDown className="w-3.5 h-3.5" /> : <ChevronRight className="w-3.5 h-3.5" />}
                              </button>
                            </td>
                            <td className="p-2">
                              <span className="font-bold text-white block">{trd.id}</span>
                              <span className="text-[9px] text-terminal-muted">{trd.journalId}</span>
                            </td>
                            <td className="p-2">
                              <span className="font-bold text-purple-300 block">{trd.aiModel}</span>
                              <span className="text-[9px] text-terminal-muted">{trd.strategy}</span>
                            </td>
                            <td className="p-2">
                              <span className="font-bold text-white block">{trd.instrument}</span>
                              <span className="text-[9px] text-terminal-amber">{trd.exchange}</span>
                            </td>
                            <td className="p-2">
                              <span className={cn("font-bold block", trd.side === 'BUY' ? "text-terminal-green" : "text-terminal-red")}>
                                {trd.side} {trd.quantity}
                              </span>
                              <span className="text-[9px] text-terminal-muted">{trd.holdingTime}</span>
                            </td>
                            <td className="p-2 font-mono">
                              <span className="text-slate-300 block">₹{trd.entryPrice.toLocaleString()}</span>
                              <span className="text-white font-bold">→ ₹{trd.exitPrice.toLocaleString()}</span>
                            </td>
                            <td className={cn("p-2 font-bold font-mono", trd.netPnl >= 0 ? "text-terminal-green" : "text-terminal-red")}>
                              {trd.netPnl >= 0 ? '+' : ''}{formatCurrency(trd.netPnl)}
                            </td>
                            <td className={cn("p-2 font-bold font-mono", trd.returnPct >= 0 ? "text-terminal-green" : "text-terminal-red")}>
                              {trd.returnPct >= 0 ? '+' : ''}{trd.returnPct}%
                            </td>
                            <td className="p-2 font-bold text-terminal-green">
                              {trd.executionQuality} / 100
                            </td>
                            <td className="p-2">
                              <span className="px-1.5 py-0.5 bg-terminal-green/20 text-terminal-green rounded text-[9px] font-bold uppercase">
                                {trd.auditStatus}
                              </span>
                            </td>
                            <td className="p-2 text-right">
                              <Button 
                                size="sm" 
                                variant="outline" 
                                onClick={(e) => { e.stopPropagation(); setSelectedTrade(trd); setActiveTab('INSPECTOR'); }}
                                className="h-6 text-[9px] px-2 border border-terminal-border hover:bg-terminal-amber/20 hover:text-terminal-amber"
                              >
                                Inspect →
                              </Button>
                            </td>
                          </tr>

                          {/* ROW EXPANSION PANEL */}
                          {isExpanded && (
                            <tr className="bg-black/80">
                              <td colSpan={11} className="p-4 space-y-3 border-b border-terminal-border">
                                <div className="flex items-center justify-between border-b border-white/10 pb-2">
                                  <span className="text-terminal-amber font-bold uppercase text-[11px] flex items-center gap-1.5">
                                    <TerminalIcon className="w-3.5 h-3.5 text-terminal-amber" /> Complete Lifecycle Audit ({trd.id})
                                  </span>
                                  <span className="text-[10px] text-terminal-muted">Certificate Hash: {trd.certificateHash.substring(0, 18)}...</span>
                                </div>
                                <p className="text-xs text-slate-200 leading-relaxed italic">
                                  "{trd.decisionReason}"
                                </p>
                                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
                                  <div className="p-2 bg-white/5 border border-terminal-border rounded space-y-1">
                                    <span className="text-[10px] text-terminal-amber font-bold block uppercase">Committee Consensus</span>
                                    {trd.committeeVotes.map((v, i) => (
                                      <div key={i} className="flex justify-between text-[10px]">
                                        <span className="text-terminal-muted">{v.agent}:</span>
                                        <strong className="text-terminal-green">{v.vote} ({v.weight * 100}%)</strong>
                                      </div>
                                    ))}
                                  </div>
                                  <div className="p-2 bg-white/5 border border-terminal-border rounded space-y-1">
                                    <span className="text-[10px] text-terminal-blue font-bold block uppercase">Risk & VaR Snapshot</span>
                                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">VaR Limit:</span><strong className="text-white">{trd.riskSnapshot.var}</strong></div>
                                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Market Beta:</span><strong className="text-white">{trd.riskSnapshot.beta}</strong></div>
                                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Max Drawdown:</span><strong className="text-terminal-red">{trd.riskSnapshot.maxDrawdown}</strong></div>
                                  </div>
                                  <div className="p-2 bg-white/5 border border-terminal-border rounded space-y-1">
                                    <span className="text-[10px] text-purple-300 font-bold block uppercase">Memory & Knowledge Graph</span>
                                    <div className="text-[10px] text-terminal-muted truncate">Memory: {trd.memoryReferences[0]}</div>
                                    <div className="text-[10px] text-terminal-muted truncate">Knowledge: {trd.knowledgeLinks[0]}</div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                          )}
                        </React.Fragment>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

            {/* RIGHT SIDE INSPECTOR */}
            {selectedTrade && (
              <div className="w-full lg:w-[380px] bg-black border-l border-terminal-border flex flex-col shrink-0 overflow-hidden font-mono text-xs">
                <div className="bg-terminal-panel p-3 border-b border-terminal-border flex items-center justify-between">
                  <div>
                    <span className="text-white font-bold text-xs uppercase flex items-center gap-1.5">
                      <ShieldCheck className="w-4 h-4 text-terminal-green" /> Quick Inspector ({selectedTrade.id})
                    </span>
                    <span className="text-[10px] text-terminal-muted block">{selectedTrade.instrument} &bull; {selectedTrade.aiModel}</span>
                  </div>
                  <span className="px-2 py-0.5 bg-terminal-green/20 text-terminal-green rounded text-[10px] font-bold uppercase">
                    {selectedTrade.tradeStatus}
                  </span>
                </div>
                <div className="p-3 space-y-3 overflow-y-auto flex-1">
                  <div className="p-2.5 bg-white/5 border border-terminal-border rounded space-y-1.5">
                    <span className="text-[10px] text-terminal-amber font-bold block uppercase">Execution Details</span>
                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Execution ID:</span><strong className="text-white">{selectedTrade.executionId}</strong></div>
                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Decision ID:</span><strong className="text-white">{selectedTrade.decisionId}</strong></div>
                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Slippage:</span><strong className="text-terminal-blue">{selectedTrade.slippageBps} bps</strong></div>
                    <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">EQS Quality:</span><strong className="text-terminal-green">{selectedTrade.executionQuality} / 100</strong></div>
                  </div>
                  <div className="p-2.5 bg-white/5 border border-terminal-border rounded space-y-1.5">
                    <span className="text-[10px] text-terminal-blue font-bold block uppercase">Knowledge & Memory</span>
                    <div className="text-[10px] text-terminal-muted">Knowledge: {selectedTrade.knowledgeVersion}</div>
                    <div className="text-[10px] text-terminal-muted">Vector: {selectedTrade.memorySnapshot}</div>
                  </div>
                  <div className="p-2.5 bg-black border border-terminal-border rounded space-y-1">
                    <span className="text-[9px] text-terminal-amber font-bold block uppercase">SHA256 Fingerprint</span>
                    <p className="text-[9px] text-terminal-muted break-all font-mono">{selectedTrade.certificateHash}</p>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* TAB 3: TIMELINE */}
        {activeTab === 'TIMELINE' && selectedTrade && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-5xl mx-auto w-full">
            <div className="bg-terminal-panel border border-terminal-border p-4 rounded space-y-4">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <div>
                  <h3 className="text-white font-bold uppercase text-sm">Institutional Trade Timeline ({selectedTrade.id})</h3>
                  <span className="text-[10px] text-terminal-muted">Chronological Audit Chain from Signal to Journal Archive</span>
                </div>
                <span className="px-2 py-1 bg-terminal-green/20 text-terminal-green rounded text-[10px] font-bold">VERIFIED WORM CHAIN</span>
              </div>
              <div className="space-y-4 border-l-2 border-terminal-border/80 pl-6 ml-2">
                {selectedTrade.timeline.map((tl, i) => (
                  <div key={i} className="relative space-y-1">
                    <span className="absolute -left-[31px] top-1 w-3.5 h-3.5 rounded-full bg-terminal-amber border-2 border-black" />
                    <div className="flex items-center gap-2 text-terminal-muted text-[10px]">
                      <span>{tl.time}</span>
                      <span className="text-terminal-green font-bold">[{tl.status}]</span>
                    </div>
                    <p className="text-white text-sm font-medium">{tl.event}</p>
                  </div>
                ))}
                <div className="relative space-y-1">
                  <span className="absolute -left-[31px] top-1 w-3.5 h-3.5 rounded-full bg-terminal-green border-2 border-black" />
                  <div className="flex items-center gap-2 text-terminal-muted text-[10px]">
                    <span>{selectedTrade.closedTime}</span>
                    <span className="text-terminal-green font-bold">[ARCHIVED]</span>
                  </div>
                  <p className="text-white text-sm font-medium">Immutable Journal & Cryptographic Certificate Sealed</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 4: REPLAY ENGINE */}
        {activeTab === 'REPLAY' && selectedTrade && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-5xl mx-auto w-full">
            <div className="bg-terminal-panel border border-terminal-border p-4 rounded space-y-4">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <div>
                  <h3 className="text-white font-bold uppercase text-sm">Institutional Replay Engine ({selectedTrade.id})</h3>
                  <span className="text-[10px] text-terminal-muted">Second-by-Second Playback of Orderbook, AI Committee, & Price Tick Stream</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button 
                    size="sm" 
                    variant="outline" 
                    onClick={() => setIsPlayingReplay(!isPlayingReplay)}
                    className="h-7 text-[10px] px-3 gap-1.5 border border-terminal-border"
                  >
                    {isPlayingReplay ? <Pause className="w-3.5 h-3.5 text-terminal-amber" /> : <Play className="w-3.5 h-3.5 text-terminal-green" />}
                    {isPlayingReplay ? 'Pause Replay' : 'Play Replay'}
                  </Button>
                  <Button 
                    size="sm" 
                    variant="outline" 
                    onClick={() => setReplayStep(1)}
                    className="h-7 text-[10px] px-3 gap-1.5 border border-terminal-border"
                  >
                    <RotateCcw className="w-3.5 h-3.5 text-terminal-blue" /> Reset
                  </Button>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="p-3 bg-black border border-terminal-border rounded space-y-2">
                  <span className="text-terminal-amber font-bold uppercase text-[10px] block">Live Playback State</span>
                  <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Playback Frame:</span><strong className="text-white">{replayStep} / 10</strong></div>
                  <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Playback Speed:</span><strong className="text-terminal-blue">{replaySpeed}x Speed</strong></div>
                  <div className="flex justify-between text-[10px]"><span className="text-terminal-muted">Model State:</span><strong className="text-terminal-green">Synced</strong></div>
                </div>
                <div className="p-3 bg-black border border-terminal-border rounded space-y-2 md:col-span-2">
                  <span className="text-terminal-blue font-bold uppercase text-[10px] block">Frame Tick Event ({selectedTrade.instrument})</span>
                  <p className="text-white text-xs">
                    {replayStep === 1 && "09:15:22 IST - Orderflow imbalance detected at VWAP support with positive institutional block accumulation."}
                    {replayStep === 2 && "09:15:25 IST - 9/9 AI Committee Quorum Achieved. Macro, Risk, and Momentum agents vote APPROVE."}
                    {replayStep === 3 && "09:15:28 IST - Smart DMA Router dispatched to NSE. Latency 9.4ms."}
                    {replayStep === 4 && `09:15:30 IST - Order executed at ₹${selectedTrade.entryPrice}. Slippage ${selectedTrade.slippageBps} bps.`}
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 5: EVIDENCE VAULT */}
        {activeTab === 'EVIDENCE' && selectedTrade && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-5xl mx-auto w-full">
            <div className="bg-terminal-panel border border-terminal-border p-4 rounded space-y-4">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <div>
                  <h3 className="text-white font-bold uppercase text-sm">Immutable Evidence Vault ({selectedTrade.evidenceId})</h3>
                  <span className="text-[10px] text-terminal-muted">WORM Snapshots, Committee Votes, AI Reasoning, and Execution Proofs</span>
                </div>
                <Button size="sm" variant="outline" onClick={() => alert("Downloading Evidence Archive...")} className="h-7 text-[10px] px-3 gap-1.5 border border-terminal-border">
                  <Download className="w-3 h-3 text-terminal-amber" /> Download Proof Bundle
                </Button>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-3 bg-black border border-terminal-border rounded space-y-2">
                  <span className="text-terminal-amber font-bold uppercase text-[10px] block">Committee & Decision Proofs</span>
                  <div className="space-y-1 text-[10px]">
                    <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Committee ID:</span><strong className="text-white">{selectedTrade.committeeId}</strong></div>
                    <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Decision ID:</span><strong className="text-white">{selectedTrade.decisionId}</strong></div>
                    <div className="flex justify-between py-1"><span className="text-terminal-muted">Quorum Consensus:</span><strong className="text-terminal-green">9/9 Unanimous</strong></div>
                  </div>
                </div>

                <div className="p-3 bg-black border border-terminal-border rounded space-y-2">
                  <span className="text-terminal-blue font-bold uppercase text-[10px] block">Cryptographic Checksum & Hash</span>
                  <div className="space-y-1 text-[10px]">
                    <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">SHA256 Hash:</span><strong className="text-terminal-green font-mono">{selectedTrade.certificateHash}</strong></div>
                    <div className="flex justify-between py-1"><span className="text-terminal-muted">Audit State:</span><strong className="text-terminal-green">VERIFIED WORM</strong></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 6: PERFORMANCE */}
        {activeTab === 'PERFORMANCE' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-5xl mx-auto w-full">
            <div className="bg-terminal-panel border border-terminal-border p-4 rounded space-y-4">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <h3 className="text-white font-bold uppercase text-sm">Advanced Performance & Analytics</h3>
                <span className="text-[10px] text-terminal-green font-bold">Sharpe Ratio: 2.94 | Sortino: 3.42</span>
              </div>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                <div className="p-3 bg-black border border-terminal-border rounded">
                  <span className="text-terminal-muted text-[10px] uppercase block">Profit Factor</span>
                  <strong className="text-white text-base">3.82</strong>
                </div>
                <div className="p-3 bg-black border border-terminal-border rounded">
                  <span className="text-terminal-muted text-[10px] uppercase block">Expectancy</span>
                  <strong className="text-terminal-green text-base">+₹18,420 / Trade</strong>
                </div>
                <div className="p-3 bg-black border border-terminal-border rounded">
                  <span className="text-terminal-muted text-[10px] uppercase block">Recovery Factor</span>
                  <strong className="text-terminal-blue text-base">14.2</strong>
                </div>
                <div className="p-3 bg-black border border-terminal-border rounded">
                  <span className="text-terminal-muted text-[10px] uppercase block">Max Drawdown</span>
                  <strong className="text-terminal-red text-base">-0.71%</strong>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* TAB 7: CERTIFICATES */}
        {activeTab === 'CERTIFICATES' && selectedTrade && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-4xl mx-auto w-full">
            <div className="bg-terminal-panel border-2 border-terminal-amber p-6 rounded-lg space-y-4 shadow-xl">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 bg-terminal-amber/20 text-terminal-amber rounded border border-terminal-amber/40">
                    <Award className="w-6 h-6" />
                  </div>
                  <div>
                    <h3 className="text-white font-bold uppercase text-sm">Institutional Trade Certificate ({selectedTrade.id})</h3>
                    <span className="text-[10px] text-terminal-muted">AI ARINA Verified Paper Trading Operating System</span>
                  </div>
                </div>
                <Button size="sm" variant="outline" onClick={() => alert("Downloading PDF Certificate...")} className="h-7 text-[10px] px-3 gap-1.5 border border-terminal-border">
                  <Download className="w-3 h-3 text-terminal-amber" /> Download PDF
                </Button>
              </div>

              <div className="grid grid-cols-2 gap-4 text-[11px] bg-black p-4 rounded border border-terminal-border">
                <div><span className="text-terminal-muted">Trade ID:</span> <strong className="text-white">{selectedTrade.id}</strong></div>
                <div><span className="text-terminal-muted">Journal ID:</span> <strong className="text-white">{selectedTrade.journalId}</strong></div>
                <div><span className="text-terminal-muted">Execution ID:</span> <strong className="text-white">{selectedTrade.executionId}</strong></div>
                <div><span className="text-terminal-muted">AI Model:</span> <strong className="text-purple-300">{selectedTrade.aiModel}</strong></div>
                <div><span className="text-terminal-muted">Net P&L:</span> <strong className="text-terminal-green">+{formatCurrency(selectedTrade.netPnl)}</strong></div>
                <div><span className="text-terminal-muted">EQS Quality:</span> <strong className="text-terminal-green">{selectedTrade.executionQuality} / 100</strong></div>
              </div>

              <div className="p-3 bg-black border border-terminal-border rounded space-y-1">
                <span className="text-[10px] text-terminal-amber font-bold uppercase block">SHA256 Cryptographic Fingerprint</span>
                <p className="text-[10px] text-terminal-muted font-mono break-all">{selectedTrade.certificateHash}</p>
              </div>
            </div>
          </div>
        )}

        {/* TAB 8: AUDIT */}
        {activeTab === 'AUDIT' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-5xl mx-auto w-full">
            <div className="bg-terminal-panel border border-terminal-border p-4 rounded space-y-4">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <h3 className="text-white font-bold uppercase text-sm">Enterprise Immutable Audit Log</h3>
                <span className="text-[10px] text-terminal-green font-bold">100% Tamperproof WORM Log</span>
              </div>
              <div className="space-y-2">
                {LIVE_EVENT_FEED.map((ev, i) => (
                  <div key={i} className="p-2.5 bg-black border border-terminal-border rounded flex items-center justify-between">
                    <div>
                      <div className="flex items-center gap-2 text-[10px] text-terminal-muted">
                        <span>{ev.time}</span>
                        <strong className="text-terminal-amber">[{ev.event}]</strong>
                      </div>
                      <p className="text-white text-[11px]">{ev.details}</p>
                    </div>
                    <span className="px-2 py-0.5 bg-terminal-green/20 text-terminal-green rounded text-[9px] font-bold">VERIFIED</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* TAB 9: INSPECTOR */}
        {activeTab === 'INSPECTOR' && selectedTrade && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 font-mono text-xs max-w-5xl mx-auto w-full">
            <div className="bg-terminal-panel border border-terminal-border p-4 rounded space-y-4">
              <div className="flex items-center justify-between border-b border-terminal-border pb-3">
                <h3 className="text-white font-bold uppercase text-sm">Deep Context Inspector ({selectedTrade.id})</h3>
                <span className="text-[10px] text-terminal-green font-bold">All Systems Linked</span>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-3 bg-black border border-terminal-border rounded space-y-2">
                  <span className="text-terminal-amber font-bold uppercase text-[10px] block">Execution & Committee State</span>
                  <div className="space-y-1 text-[10px]">
                    <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Execution ID:</span><strong className="text-white">{selectedTrade.executionId}</strong></div>
                    <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Decision ID:</span><strong className="text-white">{selectedTrade.decisionId}</strong></div>
                    <div className="flex justify-between py-1"><span className="text-terminal-muted">Committee ID:</span><strong className="text-white">{selectedTrade.committeeId}</strong></div>
                  </div>
                </div>
                <div className="p-3 bg-black border border-terminal-border rounded space-y-2">
                  <span className="text-terminal-blue font-bold uppercase text-[10px] block">Memory & Knowledge Graph Links</span>
                  <div className="space-y-1 text-[10px]">
                    <div className="flex justify-between py-1 border-b border-white/5"><span className="text-terminal-muted">Knowledge Version:</span><strong className="text-purple-300">{selectedTrade.knowledgeVersion}</strong></div>
                    <div className="flex justify-between py-1"><span className="text-terminal-muted">Vector Snapshot:</span><strong className="text-terminal-green">{selectedTrade.memorySnapshot}</strong></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* BOTTOM LIVE ENTERPRISE EVENT STREAM */}
        <div className="bg-black border-t border-terminal-border px-3 py-2 flex items-center justify-between gap-4 font-mono text-[10px] shrink-0">
          <div className="flex items-center gap-2 overflow-x-auto whitespace-nowrap">
            <span className="text-terminal-amber font-bold uppercase flex items-center gap-1">
              <TerminalIcon className="w-3 h-3 text-terminal-amber" /> Live Enterprise Stream:
            </span>
            {LIVE_EVENT_FEED.map((ev, i) => (
              <span key={i} className="text-terminal-muted px-2 py-0.5 bg-white/5 border border-terminal-border rounded flex items-center gap-1.5">
                <span className="text-white font-bold">{ev.time}</span>
                <span className="text-terminal-green">●</span>
                <span>{ev.event}: {ev.details}</span>
              </span>
            ))}
          </div>
          <span className="text-terminal-green font-bold shrink-0">100% WORM AUDIT ACTIVE</span>
        </div>

      </DataBoundary>
    </div>
  );
});
