export const FUND_TYPES = {
  MASTER_FUND: "MASTER_FUND",
  AI_MODEL_FUND: "AI_MODEL_FUND",
  STRATEGY_FUND: "STRATEGY_FUND",
  PAPER_TRADING_FUND: "PAPER_TRADING_FUND",
  RESERVE_FUND: "RESERVE_FUND",
  TEST_FUND: "TEST_FUND",
  CUSTOM_FUND: "CUSTOM_FUND",
} as const;

export type FundType = typeof FUND_TYPES[keyof typeof FUND_TYPES];

export const FUND_STATUS = {
  ACTIVE: "ACTIVE",
  FROZEN: "FROZEN",
  ARCHIVED: "ARCHIVED",
} as const;

export type FundStatus = typeof FUND_STATUS[keyof typeof FUND_STATUS];

export const FUND_OPERATIONS = {
  CREATE: "CREATE",
  ALLOCATE: "ALLOCATE",
  RESERVE: "RESERVE",
  RELEASE: "RELEASE",
  FREEZE: "FREEZE",
  UNFREEZE: "UNFREEZE",
  TRANSFER: "TRANSFER",
  ARCHIVE: "ARCHIVE",
} as const;

export type FundOperation = typeof FUND_OPERATIONS[keyof typeof FUND_OPERATIONS];

export const ALLOCATION_STRATEGIES = {
  EQUAL: "EQUAL",
  WEIGHTED: "WEIGHTED",
  PRIORITY: "PRIORITY",
  PERCENTAGE: "PERCENTAGE",
  MANUAL: "MANUAL",
  CUSTOM: "CUSTOM",
} as const;

export type AllocationStrategy = typeof ALLOCATION_STRATEGIES[keyof typeof ALLOCATION_STRATEGIES];

export const FUND_PIPELINE_STAGES = {
  REQUEST: "REQUEST",
  VALIDATE_GOVERNANCE: "VALIDATE_GOVERNANCE",
  VALIDATE_FUNDS: "VALIDATE_FUNDS",
  VALIDATE_LIMITS: "VALIDATE_LIMITS",
  ALLOCATE_RESERVE: "ALLOCATE_RESERVE",
  AUDIT: "AUDIT",
  READY: "READY",
} as const;

export type PipelineStage = typeof FUND_PIPELINE_STAGES[keyof typeof FUND_PIPELINE_STAGES];
